FROM node:20-alpine AS deps
WORKDIR /app
RUN apk add --no-cache openssl

COPY package*.json ./
COPY apps/api/package*.json apps/api/
COPY apps/web/package*.json apps/web/
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /app
ENV DATABASE_URL="postgresql://postgres:postgres@localhost:5432/flop_club?schema=public"
RUN apk add --no-cache openssl

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run prisma:generate:prod --workspace @flop-club/api
RUN npm run build --workspace @flop-club/api

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache openssl

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY --from=build /app/apps/api/package.json ./apps/api/package.json
COPY --from=build /app/apps/api/dist ./apps/api/dist
COPY --from=build /app/apps/api/prisma ./apps/api/prisma

EXPOSE 4000
CMD ["node", "apps/api/dist/index.js"]
